### PR TITLE
Trade history coinnect bitstamp

### PR DESCRIPTION
**Pull request by ainestal**
Implement the trade history. The default output, not specifying start or end.

### CODE REVIEW

**Comment by hugues31** [comment]
Great! But could you please use the new Pair BTC_USD and unimplemented!() before I merge ?

**Comment by ainestal** [comment]
I messed up with the merges, I had the changes just before yours. Let me fix it

**Comment by ainestal** [comment]
Sorry about that. Not it includes your changes in master.

**Comment by hugues31** [comment]
Thanks :) I merge now

**Pull request merged**
