### PR TITLE
Include BitstampApi. Returning tick and tests

### PR DESCRIPTION
**Pull request by ainestal**
Creating Bitstamp and including some tests for it.
Implemented "return_ticker" and all the methods that it needs.
I followed the style of the Poloniex client in this library.
In this pull request I just want to set a common ground and ask for feedback. Since there are no tests yet I introduced these as an example, although they work.

### CODE REVIEW

**Comment by hugues31** [comment]
Thanks!
I didn't expect a PR so much as this project is in an alpha stage at this moment. I think the general API could be more generic across different exchanges, so the style is not well defined (nor tests).
I merge your commit ;)

**Comment by ainestal** [comment]
Agree. I'd like to continue with the Bitstamp api, but I don't know how you want to organise the code. I was following your code from Poloniex so the naming and structure is similar.

**Comment by hugues31** [comment]
You can go with the actual style for now if you want to contribute. You could also commit a new API style as I have no idea on how to improve it.

Maybe a main structure like this:
```
let my_api = Coinnect::new(Exchange::Kraken, "api_key", "api_secret");

let ticker = my_api.get_ticker(Pair::BTC_USD); // <- the return type must be identical for all exchanges
```

But I don't know how to implement it (I'm fairly new to Rust)

**Comment by ainestal** [comment]
That sounds sensible. I will continue using Poloniex as the example as much as possible to keep some consistency.

Btw, I'm also fairly new to Rust

**Comment by someGenericUsername** [comment]
I think I'm going to try to implement it, but I must say I am new to rust, too.

**Comment by someGenericUsername** [comment]
Just so you don't wait for it, I am not going to implement it, as I only need a small subset of the library and it would be pointless for me to refactor the whole code and create a consistent api if there already exists a consistent api https://cryptowatch.es/docs/api that I could easily wrap and covers my needs.

**Pull request merged**
