### PR TITLE
Refactorization to create a generic api

### PR DESCRIPTION
**Pull request by ainestal**
Begining of the refactorization of the library to create a generic api to use with all the different exchanges.

This is a proposal, please give me feedback. The idea is to implement what was referenced in #1 . In order to do that I'm trying to standarise the different libraries, starting with Bitstamp. A trait is implemented so all the apis of the different exchanges have to implement it, thus creating a standard way of using them.

### CODE REVIEW

**Comment by hugues31** [comment]
This is typically the thing I wanted to implement. I don't have time to review your code for now but I'll do it very soon :)

**Comment by ainestal** [comment]
I will continue working on this generic api solution. My idea is to implement it for Bitstamp so it works for some exchange as soon as possible, and then do the rest of exchanges.
Hopefully after the standarisation, creating the rest of exchanges is easier since it's just follow the trait and include it in the list of available exchanges.

**Comment by hugues31** [comment]
For what I have seen, I agree with your design. I will take a deeper look this weekend :)

**Comment by ainestal** [comment]
Now it's possible to use any exchange with the same interface (coinnect). The exchanges must implement the trait ExchangeApi. It specifies the main functions to interact with the exchanges from the high point of view of an application.

The functions new and new_from_file are left outside the train on purpose, since otherwise generics should be use for the return values, hugely messing the code, and they are mandatory anyway. 

I also tried the possibility of having 2 traits, one is ExchangeApi and the other one ExchangeApiConstructor. It forces to import both of them all the time, it's annoying. The other option would be to create a trait implementing the other 2 traits, but after some research looks like it's not possible for now.

I have to thank you a teammate for helping me with this, it was a difficult problem to solve for a beginner, thx A!

**Comment by ainestal** [comment]
One of the problems I see now is how to standarise the output coming from the different exchanges. As you said in your comment in #1 it is mandatory that the data for all the exchanges comes in exactly the same way. That will have to be treated in each of the exchange modules (BitstampApi, KrakenApi, PoloniexApi, etc). I think that is the next problem to solve.

@hugues31 please let me know your thoughts. I'm pushing all the changes to the same branch to have continuity and avoid unnecessary confusion between branches and PRs, since all of them are in the same direction.

**Comment by hugues31** [comment]
I'm starting to review your code. I think I will merge this PR and will continue the changes for the Kraken and Poloniex API.

**Comment by ainestal** [comment]
I think there are 2 ways to solve the standardization of the output:
1. The wrapper functions that you describe: implies that the general coinnect needs specific knowledge about the format coming from each of the exchanges
2. Types for the returned output that the different exchanges have to implement and return

I was thinking about the problem and option 2 seems better since all the logic related to a specific exchange remains within the module of the exchange. That would mean that modules could be use from coinnect or on their own.

We can use the `Result` in both approaches, as you suggest.

**Comment by hugues31** [comment]
May I ask you why you have use a `Box<ExchangeApi>` instead of a regular `ExchangeApi` for the return type of `new` and `new_from_file` ?

**Comment by ainestal** [comment]
It's because I needed a reference to a Trait, `ExchangeApi`, and boxes are the perfect way of doing that since they own their content. That trait then will actually be a specific exchange in specific implementations, so all of those implementations can be encapsulated in the Box.

It also didn't compile without the Box :D

**Comment by hugues31** [comment]
Ok, thanks 😄

**Comment by ainestal** [comment]
It feels like unnecessary but it actually works. I spent some time trying to figure out how to unbox the object to be able to use. The cool thing about it is that the Box is just a reference, so there is actually no need to unbox anything, we can use it straight away.

The only problem I'm having with it is that the rust plugin for Intellij doesn't recognise the methods of the object after the boxing.

**Pull request merged**
